/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package realstatepanel;

import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static realstatepanel.AdmincreationFormAdmin.currentAdminId;

/**
 *
 * @author My Computer
 */
public class AdminListingForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminListingForm
     */
    public static int currentAdminId;
    public AdminListingForm() {
        initComponents();
        populateJTable();
        this.setLocationRelativeTo(null);
        
        JThousing.setShowGrid(true);
        JThousing.setGridColor(Color.RED);
        JThousing.setSelectionBackground(Color.LIGHT_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTFPropID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTFPropType = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JTFaddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JTFCity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JTFProv = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JTFDescription = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        JTFbathroom = new javax.swing.JTextField();
        JTFbedroom = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        JTFSQFT = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        JTFPrice = new javax.swing.JTextField();
        JTFlastAgent = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        JTFowner = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        JTFPhone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JThousing = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AgentLogout = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnAdminCreation = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        EmpID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTFPropID.setForeground(new java.awt.Color(0, 0, 0));
        JTFPropID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFPropIDActionPerformed(evt);
            }
        });
        getContentPane().add(JTFPropID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 108, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Property ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, 60));

        JTFPropType.setForeground(new java.awt.Color(0, 0, 0));
        JTFPropType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFPropTypeActionPerformed(evt);
            }
        });
        getContentPane().add(JTFPropType, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 171, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Property Type: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, 60));

        JTFaddress.setForeground(new java.awt.Color(0, 0, 0));
        JTFaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFaddressActionPerformed(evt);
            }
        });
        getContentPane().add(JTFaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 154, 64));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Address: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, 60));

        JTFCity.setForeground(new java.awt.Color(0, 0, 0));
        JTFCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCityActionPerformed(evt);
            }
        });
        getContentPane().add(JTFCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 171, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("City: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, 60));

        JTFProv.setForeground(new java.awt.Color(0, 0, 0));
        JTFProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFProvActionPerformed(evt);
            }
        });
        getContentPane().add(JTFProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 171, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Province : ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, 60));

        JTFDescription.setForeground(new java.awt.Color(0, 0, 0));
        JTFDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFDescriptionActionPerformed(evt);
            }
        });
        getContentPane().add(JTFDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 216, 82));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Description : ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, 60));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("No. Bathrooms : ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, 60));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("No. Bedrooms : ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, 60));

        JTFbathroom.setForeground(new java.awt.Color(0, 0, 0));
        JTFbathroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFbathroomActionPerformed(evt);
            }
        });
        getContentPane().add(JTFbathroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 214, -1));

        JTFbedroom.setForeground(new java.awt.Color(0, 0, 0));
        JTFbedroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFbedroomActionPerformed(evt);
            }
        });
        getContentPane().add(JTFbedroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 214, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Square Footage : ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, 60));

        JTFSQFT.setForeground(new java.awt.Color(0, 0, 0));
        JTFSQFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFSQFTActionPerformed(evt);
            }
        });
        getContentPane().add(JTFSQFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 214, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Price(PHP) : ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, 60));

        JTFPrice.setForeground(new java.awt.Color(0, 0, 0));
        JTFPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFPriceActionPerformed(evt);
            }
        });
        getContentPane().add(JTFPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 214, -1));

        JTFlastAgent.setForeground(new java.awt.Color(0, 0, 0));
        JTFlastAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFlastAgentActionPerformed(evt);
            }
        });
        getContentPane().add(JTFlastAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 90, 166, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Last Update AgentID: ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, -1, 60));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Owner Name : ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, -1, 60));

        JTFowner.setForeground(new java.awt.Color(0, 0, 0));
        JTFowner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFownerActionPerformed(evt);
            }
        });
        getContentPane().add(JTFowner, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 140, 166, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Owner Phone#: ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 160, -1, 60));

        JTFPhone.setForeground(new java.awt.Color(0, 0, 0));
        JTFPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(JTFPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 180, 166, -1));

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 230, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Delete");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 230, 69, -1));

        jButton3.setBackground(new java.awt.Color(51, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 230, 69, -1));

        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        JThousing.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        JThousing.setForeground(new java.awt.Color(0, 0, 0));
        JThousing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JThousing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JThousingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JThousing);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 1090, 320));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("X");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("_");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Agent ID:");

        AgentLogout.setForeground(new java.awt.Color(255, 51, 51));
        AgentLogout.setText("Log out");
        AgentLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgentLogoutMouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(204, 204, 255));
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("LOGO");
        jLabel9.setOpaque(true);

        jButton4.setBackground(new java.awt.Color(51, 255, 255));
        jButton4.setText("Listing");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 255, 255));
        jButton5.setText("Document");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnAdminCreation.setBackground(new java.awt.Color(102, 102, 255));
        btnAdminCreation.setText("Admin");
        btnAdminCreation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminCreationActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(51, 255, 255));
        jButton7.setText("Agent");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Account Creation");

        EmpID.setForeground(new java.awt.Color(0, 0, 0));
        EmpID.setText("ID");

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(AgentLogout)
                            .addComponent(btnAdminCreation, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmpID)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnAdminCreation, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmpID)
                .addGap(5, 5, 5)
                .addComponent(AgentLogout)
                .addGap(123, 123, 123))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void populateJTable(){
    
        DataQuery dq = new DataQuery();
        ArrayList<housingdata> adlist = dq.HousingList();
        String[] colNames = {"propertyID","propertyType","Address","City","Province","nobedroom","nobathroom","propertysqft","propertyPrice","Description","LastUpdateAdmin","ownerID"};
        Object[][] rows = new Object[adlist.size()][12]; 
        
        for(int i = 0; i < adlist.size(); i++){
            rows[i][0] = adlist.get(i).getPropertyID();
            rows[i][1] = adlist.get(i).getPropertyType();
            rows[i][2] = adlist.get(i).getAddress();
            rows[i][3] = adlist.get(i).getCity();
            rows[i][4] = adlist.get(i).getProvince();
            rows[i][5] = adlist.get(i).getNobedroom();
            rows[i][6] = adlist.get(i).getNobathroom();
            rows[i][7] = adlist.get(i).getPropertysqft();
            rows[i][8] = adlist.get(i).getPropertyPrice();
            rows[i][9] = adlist.get(i).getDescription();
            rows[i][10] = adlist.get(i).getLastUpdateAdmin();
            rows[i][11] = adlist.get(i).getOwnerID();
      
           
        }
        MyModel  mmd = new MyModel(rows , colNames);
        JThousing.setModel(mmd);
        JThousing.setRowHeight(40);
        JThousing.getColumnModel().getColumn(11).setPreferredWidth(120);
    }
    
    private void JTFPropIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFPropIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFPropIDActionPerformed

    private void JTFPropTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFPropTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFPropTypeActionPerformed

    private void JTFaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFaddressActionPerformed

    private void JTFCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFCityActionPerformed

    private void JTFProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFProvActionPerformed

    private void JTFDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFDescriptionActionPerformed

    private void JTFbathroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFbathroomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFbathroomActionPerformed

    private void JTFbedroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFbedroomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFbedroomActionPerformed

    private void JTFSQFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFSQFTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFSQFTActionPerformed

    private void JTFPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFPriceActionPerformed

    private void JTFlastAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFlastAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFlastAgentActionPerformed

    private void JTFownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFownerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFownerActionPerformed

    private void JTFPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFPhoneActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void AgentLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgentLogoutMouseClicked
        AgentForm Agef = new AgentForm();
        Agef.setVisible(true);
        Agef.pack();
        Agef.setLocationRelativeTo(null);
        Agef.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_AgentLogoutMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        TransactionForm TF = new TransactionForm();
        TF.setVisible(true);
        TF.pack();
        TF.setLocationRelativeTo(null);
        TF.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        TransactionForm.currentAdminId = currentAdminId;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnAdminCreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminCreationActionPerformed
        // Dito po gumagawa ng admin account pero need po muna ng first admin account mula sa database
        AdmincreationFormAdmin adminCF = new AdmincreationFormAdmin();
        adminCF.setVisible(true);
        adminCF.pack();
        adminCF.setLocationRelativeTo(null);
        adminCF.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnAdminCreationActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
    }//GEN-LAST:event_jButton4ActionPerformed

    public boolean verifData(){

            if(JTFPropID.getText().equals("") && JTFPropType.getText().equals("")
                    || JTFaddress.getText().equals("") || JTFCity.getText().equals("")||
                    JTFProv.getText().equals("")|| JTFDescription.getText().equals("")
                    ||JTFlastAgent.getText().equals("") || JTFowner.getText().equals("")
                    || JTFPhone.getText().equals("") ||JTFbedroom.getText().equals("") || 
                    JTFbathroom.getText().equals("") || JTFSQFT.getText().equals("") 
                    || JTFPrice.getText().equals("") 
                     )
            {
                JOptionPane.showMessageDialog(null, "One or more Field are Empty!");
                return false;
            }
            else{
                return true;
            }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            if (verifData()){
      
        
        
        
        int propid = Integer.parseInt(JTFPropID.getText());
        String proptype = JTFPropType.getText();
        String propaddress = JTFaddress.getText();
        String propcity = JTFCity.getText();
        String propprov = JTFProv.getText();
        String Descrip = JTFDescription.getText();
        String lastagent = JTFlastAgent.getText();
        String owner = JTFowner.getText();
        int nobenroom = Integer.parseInt(JTFbedroom.getText());
        int nobath = Integer.parseInt(JTFbathroom.getText());
        int sqft = Integer.parseInt(JTFSQFT.getText());
        int price = Integer.parseInt(JTFPrice.getText());
      
        
        
        
        
        try {

            housingdata c = new housingdata(null, proptype, propaddress, propcity, propprov, nobenroom, nobath, sqft, price, Descrip, lastagent, owner);
            DataQuery dq = new DataQuery();
            dq.inserthousing(c);
            refreshJTable();
            clearFields();
           
            
            

                    } catch (Exception ex) {
            java.util.logging.Logger.getLogger(AdmincreationFormAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void JThousingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JThousingMouseClicked
        
         int rowIndex = JThousing.getSelectedRow();
        
        JTFPropID.setText(JThousing.getValueAt(rowIndex, 0).toString());
        JTFPropType.setText(JThousing.getValueAt(rowIndex, 1).toString());
        JTFaddress.setText(JThousing.getValueAt(rowIndex, 2).toString());
        JTFCity.setText(JThousing.getValueAt(rowIndex, 3).toString());
        JTFProv.setText(JThousing.getValueAt(rowIndex, 4).toString());
        JTFbedroom.setText(JThousing.getValueAt(rowIndex, 5).toString());
        JTFbathroom.setText(JThousing.getValueAt(rowIndex, 6).toString());
        JTFSQFT.setText(JThousing.getValueAt(rowIndex, 7).toString());
        JTFPrice.setText(JThousing.getValueAt(rowIndex, 8).toString());
        JTFDescription.setText(JThousing.getValueAt(rowIndex, 9).toString());
        JTFlastAgent.setText(JThousing.getValueAt(rowIndex, 10).toString());
        JTFowner.setText(JThousing.getValueAt(rowIndex, 11).toString());
    }//GEN-LAST:event_JThousingMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void refreshJTable(){
        
        JThousing.setModel(new DefaultTableModel());
        
        populateJTable();
    }
    
    public void clearFields(){
        JTFPropID.setText("");
        JTFPropType.setText("");
        JTFaddress.setText("");
        JTFCity.setText("");
        JTFProv.setText("");
        JTFDescription.setText("");
        JTFlastAgent.setText("");
        JTFowner.setText("");
        JTFbedroom.setText("");
        JTFbathroom.setText("");
        JTFSQFT.setText("");
        JTFPrice.setText("");
        JTFPhone.setText("");
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminListingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminListingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminListingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminListingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminListingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgentLogout;
    private javax.swing.JLabel EmpID;
    private javax.swing.JTextField JTFCity;
    private javax.swing.JTextField JTFDescription;
    private javax.swing.JTextField JTFPhone;
    private javax.swing.JTextField JTFPrice;
    private javax.swing.JTextField JTFPropID;
    private javax.swing.JTextField JTFPropType;
    private javax.swing.JTextField JTFProv;
    private javax.swing.JTextField JTFSQFT;
    private javax.swing.JTextField JTFaddress;
    private javax.swing.JTextField JTFbathroom;
    private javax.swing.JTextField JTFbedroom;
    private javax.swing.JTextField JTFlastAgent;
    private javax.swing.JTextField JTFowner;
    private javax.swing.JTable JThousing;
    private javax.swing.JButton btnAdminCreation;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
