/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package realstatepanel;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author My Computer
 */
public class AdmincreationFormAdmin extends javax.swing.JFrame {

    /**
     * Creates new form AdmincreationFormAdmin
     */
       public static int currentAdminId;

    public AdmincreationFormAdmin() {
        initComponents();
        populateJTable();
        this.setLocationRelativeTo(null);
        
        jTableAdminListing.setShowGrid(true);
        jTableAdminListing.setGridColor(Color.RED);
        jTableAdminListing.setSelectionBackground(Color.LIGHT_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAdminListing = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        JTFLname = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        JTFMinitial = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JTFFname = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        JTFPhone = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        JTFId = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        JpassAdmin = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AgentLogout = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JBListing = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        EmpID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("X");
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("_");
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });

        jTableAdminListing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableAdminListing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAdminListingMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableAdminListing);

        jLabel6.setText("ADMIN LISTING FORM");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));
        jPanel2.setLayout(null);

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Employee userName:");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(100, 80, 120, 16);

        JTFLname.setForeground(new java.awt.Color(0, 0, 0));
        JTFLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFLnameActionPerformed(evt);
            }
        });
        jPanel2.add(JTFLname);
        JTFLname.setBounds(230, 170, 166, 24);

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Employee L Name:");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(110, 170, 104, 16);

        username.setForeground(new java.awt.Color(0, 0, 0));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username);
        username.setBounds(230, 80, 166, 24);

        JTFMinitial.setForeground(new java.awt.Color(0, 0, 0));
        JTFMinitial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFMinitialActionPerformed(evt);
            }
        });
        jPanel2.add(JTFMinitial);
        JTFMinitial.setBounds(230, 200, 166, 24);

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Employee M Initial:");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(110, 200, 104, 16);

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Employee Phone:");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(110, 230, 97, 16);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Add Admin Account");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(200, 20, 174, 24);

        JTFFname.setForeground(new java.awt.Color(0, 0, 0));
        JTFFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFFnameActionPerformed(evt);
            }
        });
        jPanel2.add(JTFFname);
        JTFFname.setBounds(230, 140, 166, 24);

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Employee F Name:");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(110, 140, 103, 16);

        JTFPhone.setForeground(new java.awt.Color(0, 0, 0));
        JTFPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFPhoneActionPerformed(evt);
            }
        });
        jPanel2.add(JTFPhone);
        JTFPhone.setBounds(230, 230, 166, 24);

        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Employee Password:");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(100, 110, 119, 16);

        JTFId.setForeground(new java.awt.Color(0, 0, 0));
        JTFId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFIdActionPerformed(evt);
            }
        });
        jPanel2.add(JTFId);
        JTFId.setBounds(230, 50, 166, 24);

        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("ID :");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(200, 50, 20, 16);
        jPanel2.add(JpassAdmin);
        JpassAdmin.setBounds(230, 110, 170, 24);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Agent ID:");

        AgentLogout.setForeground(new java.awt.Color(255, 51, 51));
        AgentLogout.setText("Log out");
        AgentLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgentLogoutMouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(204, 204, 255));
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("LOGO");
        jLabel9.setOpaque(true);

        JBListing.setBackground(new java.awt.Color(51, 255, 255));
        JBListing.setText("Listing");
        JBListing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBListingMouseClicked(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 255, 255));
        jButton5.setText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 102, 255));
        jButton6.setText("Admin");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(51, 255, 255));
        jButton7.setText("Agent");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Account Creation");

        EmpID.setForeground(new java.awt.Color(0, 0, 0));
        EmpID.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(AgentLogout)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBListing, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmpID)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(JBListing)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addGap(73, 73, 73)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmpID)
                .addGap(5, 5, 5)
                .addComponent(AgentLogout)
                .addGap(123, 123, 123))
        );

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(783, 783, 783)
                                .addComponent(jLabel30)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel29)
                                .addGap(29, 29, 29))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jButton1)
                        .addGap(20, 20, 20)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel30)
                        .addComponent(jLabel29)))
                .addGap(34, 34, 34)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void populateJTable(){
    
        DataQuery dq = new DataQuery();
        ArrayList<admindata> adlist = dq.AdminAccountList(currentAdminId);
        String[] colNames = {"Id","username","Password","First Name","Last Name","M. Initial","phone"};
        Object[][] rows = new Object[adlist.size()][7]; 
        
        for(int i = 0; i < adlist.size(); i++){
            rows[i][0] = adlist.get(i).getId();
            rows[i][1] = adlist.get(i).getUsername();
            rows[i][2] = adlist.get(i).getPass();
            rows[i][3] = adlist.get(i).getFname();
            rows[i][4] = adlist.get(i).getLname();
            rows[i][5] = adlist.get(i).getMinitial();
            rows[i][6] = adlist.get(i).getPhone();
      
           
        }
        MyModel  mmd = new MyModel(rows , colNames);
        jTableAdminListing.setModel(mmd);
        jTableAdminListing.setRowHeight(40);
        jTableAdminListing.getColumnModel().getColumn(6).setPreferredWidth(120);
    }

    private void showData(int index){
        JTFId.setText(jTableAdminListing.getValueAt(index, 1).toString());
        username.setText(jTableAdminListing.getValueAt(index, 2).toString());
        JpassAdmin.setText(jTableAdminListing.getValueAt(index, 3).toString());
        JTFFname.setText(jTableAdminListing.getValueAt(index, 4).toString());
        JTFLname.setText(jTableAdminListing.getValueAt(index, 5).toString());
        JTFMinitial.setText(jTableAdminListing.getValueAt(index, 6).toString());
        JTFPhone.setText(jTableAdminListing.getValueAt(index, 7).toString());
        
    }
    
    public void clearFields(){
        JTFId.setText("");
        username.setText("");
        JpassAdmin.setText("");
        JTFFname.setText("");
        JTFLname.setText("");
        JTFMinitial.setText("");
        JTFPhone.setText("");
        
    }

    
    
    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void JTFFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFFnameActionPerformed

    private void JTFLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFLnameActionPerformed

    private void JTFMinitialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFMinitialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFMinitialActionPerformed

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        AdminListingForm AdminL = new AdminListingForm();
        AdminL.setVisible(true);
        AdminL.pack();
        AdminL.setLocationRelativeTo(null);
        AdminL.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void AgentLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgentLogoutMouseClicked
        AgentForm Agef = new AgentForm();
        Agef.setVisible(true);
        Agef.pack();
        Agef.setLocationRelativeTo(null);
        Agef.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_AgentLogoutMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void JTFPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFPhoneActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (verifData()){
      
        
        
        
        String user = username.getText();
        String pass = JpassAdmin.getText();
        String fname = JTFFname.getText();
        String lname = JTFLname.getText();
        String minitial = JTFMinitial.getText();
        String phone = JTFPhone.getText();
      
        
        
        
        
        try {

            admindata c = new admindata(null, user, pass, fname, lname, minitial, phone, currentAdminId);
            DataQuery dq = new DataQuery();
            dq.insertAdminAcc(c);
            refreshJTable();
            clearFields();
           
            
            if (isUsernameExist(username.getText())){
                JOptionPane.showMessageDialog(null, "Username Already Existed");
            }

                    } catch (Exception ex) {
            java.util.logging.Logger.getLogger(AdmincreationFormAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (!JTFId.getText().equals(""))
        {
        Integer id = Integer.valueOf(JTFId.getText());
        DataQuery dq = new DataQuery();
        dq.deleteAdminAccount(id);
//        clearFields();
//        refreshJTable();
        }else{
            JOptionPane.showMessageDialog(null, "Select a Contact from Table");
        }
        refreshJTable();
        clearFields();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JTFIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFIdActionPerformed

    private void jTableAdminListingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAdminListingMouseClicked
        // TODO add your handling code here:
        
        int rowIndex = jTableAdminListing.getSelectedRow();
//        JTFId.setText(jTableAdminListing.getValueAt(rowIndex, 0).toString());
        JTFId.setText(jTableAdminListing.getValueAt(rowIndex, 0).toString());
        username.setText(jTableAdminListing.getValueAt(rowIndex, 1).toString());
        JpassAdmin.setText(jTableAdminListing.getValueAt(rowIndex, 2).toString());
        JTFFname.setText(jTableAdminListing.getValueAt(rowIndex, 3).toString());
        JTFLname.setText(jTableAdminListing.getValueAt(rowIndex, 4).toString());
        JTFMinitial.setText(jTableAdminListing.getValueAt(rowIndex, 5).toString());
        JTFPhone.setText(jTableAdminListing.getValueAt(rowIndex, 6).toString());
         
    }//GEN-LAST:event_jTableAdminListingMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(!JTFId.getText().equals("")){
            int id = Integer.valueOf(JTFId.getText());
            String user = username.getText();
            String pass = JpassAdmin.getText();
            String fname = JTFFname.getText();
            String lname = JTFLname.getText();
            String minitial = JTFMinitial.getText();
            String phone = JTFPhone.getText();
            
            
            admindata a = new admindata(id,user ,pass ,fname , lname, minitial , phone ,currentAdminId);
                DataQuery dq = new DataQuery();
                dq.updateAdminAccount(a);    
        }
        
        
        refreshJTable();
        clearFields();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JBListingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBListingMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JBListingMouseClicked
    public void refreshJTable(){
        
        jTableAdminListing.setModel(new DefaultTableModel());
        
        populateJTable();
    }
    
    
    public boolean isUsernameExist(String un){
        boolean uExist = false;
        Connection con = MyConnection.getConnection();
        PreparedStatement ps;
        ResultSet rs;
        
        try {
            ps = con.prepareStatement("SELECT * FROM `adminacc` WHERE `username` = ? ");
            ps.setString(1, username.getText());
            
            rs = ps.executeQuery();
            
            if (rs.next()){
                uExist = true;
            }
            
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return uExist;
    }
    
    public boolean verifData(){

            if(JTFFname.getText().equals("") && JTFLname.getText().equals("")
                    || username.getText().equals("") 
                    || String.valueOf(JpassAdmin.getText()).equals(""))
            {
                JOptionPane.showMessageDialog(null, "One or more Field are Empty!");
                return false;
            }
            else if (!String.valueOf(JpassAdmin.getText()).equals(String.valueOf(JpassAdmin.getText()))){
                JOptionPane.showMessageDialog(null, "Incorrect Password!!");
                return false;
            }else{
                return true;
            }

    //        return false;
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmincreationFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmincreationFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmincreationFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmincreationFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmincreationFormAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgentLogout;
    private javax.swing.JLabel EmpID;
    private javax.swing.JButton JBListing;
    private javax.swing.JTextField JTFFname;
    private javax.swing.JTextField JTFId;
    private javax.swing.JTextField JTFLname;
    private javax.swing.JTextField JTFMinitial;
    private javax.swing.JTextField JTFPhone;
    private javax.swing.JTextField JpassAdmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAdminListing;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
