/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package realstatepanel;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author My Computer
 */
public class AGENT_ADD extends javax.swing.JFrame {

    /**
     * Creates new form AGENT_ADD
     */
        String imagePth = null;

    public AGENT_ADD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        BTNviewAgent = new javax.swing.JButton();
        BTNAddAgent = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        logo1 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        LBLAgent = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        JTFfname = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        JTFlname = new javax.swing.JTextField();
        LBLPIC = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        JTFphone = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        JTFusername = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        JTFpassword = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        LBLBrowse = new javax.swing.JButton();
        LBLBrowse1 = new javax.swing.JButton();
        BTNADDAGENT = new javax.swing.JButton();
        LBLBrowse3 = new javax.swing.JButton();
        BTNviewAgent1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        jLabel56.setForeground(new java.awt.Color(0, 0, 0));
        jLabel56.setText("ADMIN:");

        jLabel57.setText("jLabel8");

        jLabel59.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 0, 0));
        jLabel59.setText("X");
        jLabel59.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel59.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel59MouseClicked(evt);
            }
        });

        jLabel60.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 0, 0));
        jLabel60.setText("_");
        jLabel60.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel60MouseClicked(evt);
            }
        });

        BTNviewAgent.setText("VIEW AGENTS");
        BTNviewAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNviewAgentActionPerformed(evt);
            }
        });

        BTNAddAgent.setText("ADD AGENT");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(BTNAddAgent)
                .addGap(18, 18, 18)
                .addComponent(BTNviewAgent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 922, Short.MAX_VALUE)
                .addComponent(jLabel56)
                .addGap(61, 61, 61)
                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel60)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel59)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel56)
                        .addComponent(BTNviewAgent)
                        .addComponent(BTNAddAgent))
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel59)
                        .addComponent(jLabel60)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 1500, -1));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/realstatepanel/Untitled-4.jpg"))); // NOI18N
        jPanel13.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 17, 179, -1));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/realstatepanel/Untitled-6.jpg"))); // NOI18N
        jPanel13.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 206, -1, -1));

        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("DASHBOARD");
        jPanel13.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 278, -1, -1));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/realstatepanel/Human.jpg"))); // NOI18N
        jPanel13.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jLabel52.setForeground(new java.awt.Color(0, 0, 0));
        jLabel52.setText("AGENT");
        jPanel13.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/realstatepanel/House.jpg"))); // NOI18N
        jPanel13.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 461, -1, -1));

        jLabel54.setForeground(new java.awt.Color(0, 0, 0));
        jLabel54.setText("PROPERTY");
        jPanel13.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 533, -1, -1));

        LBLAgent.setBackground(new java.awt.Color(204, 204, 204));
        LBLAgent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LBLAgent.setOpaque(true);
        jPanel13.add(LBLAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 180, 120));

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 950));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setPreferredSize(new java.awt.Dimension(1500, 722));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1483, 512, -1, -1));

        jPanel18.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(4060, 512, -1, -1));

        jPanel19.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(4415, 512, -1, -1));

        jLabel58.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 0, 0));
        jLabel58.setText("AGENT /");
        jPanel15.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel61.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 0, 0));
        jLabel61.setText("FIRST NAME :");
        jPanel15.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        JTFfname.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.add(JTFfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 320, 50));

        jLabel62.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(0, 0, 0));
        jLabel62.setText("ACCOUNT INFORMATION");
        jPanel15.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        JTFlname.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.add(JTFlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 320, 50));

        LBLPIC.setBackground(new java.awt.Color(204, 204, 204));
        LBLPIC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LBLPIC.setForeground(new java.awt.Color(0, 0, 0));
        LBLPIC.setOpaque(true);
        jPanel15.add(LBLPIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 130, 120));

        jLabel64.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(0, 0, 0));
        jLabel64.setText("PHONE NUMBER :");
        jPanel15.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        JTFphone.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.add(JTFphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 320, 50));
        jPanel15.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 1580, 30));

        jLabel65.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(0, 0, 0));
        jLabel65.setText("ADD AGENT");
        jPanel15.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel66.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(0, 0, 0));
        jLabel66.setText("AGENT INFORMATION");
        jPanel15.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        JTFusername.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.add(JTFusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 320, 50));

        jLabel67.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(0, 0, 0));
        jLabel67.setText("USERNAME :");
        jPanel15.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, -1));

        jLabel68.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(0, 0, 0));
        jLabel68.setText("PASSWORD :");
        jPanel15.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, -1, -1));

        JTFpassword.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.add(JTFpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 320, 50));

        jLabel69.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(0, 0, 0));
        jLabel69.setText("LAST NAME :");
        jPanel15.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, -1));

        jLabel70.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(0, 0, 0));
        jLabel70.setText("PICTURE :");
        jPanel15.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));
        jPanel15.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 100, 30));

        jLabel63.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(0, 0, 0));
        jLabel63.setText("AGENT NUMBER :");
        jPanel15.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 130, -1));

        LBLBrowse.setText("DELETE");
        jPanel15.add(LBLBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 690, -1, -1));

        LBLBrowse1.setText("Browse");
        LBLBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LBLBrowse1ActionPerformed(evt);
            }
        });
        jPanel15.add(LBLBrowse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, -1, -1));

        BTNADDAGENT.setText("ADD");
        BTNADDAGENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNADDAGENTActionPerformed(evt);
            }
        });
        jPanel15.add(BTNADDAGENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 690, -1, -1));

        LBLBrowse3.setText("UPDATE");
        jPanel15.add(LBLBrowse3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 690, -1, -1));

        BTNviewAgent1.setText("SEARCH");
        BTNviewAgent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNviewAgent1ActionPerformed(evt);
            }
        });
        jPanel15.add(BTNviewAgent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));

        getContentPane().add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel59MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel59MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel59MouseClicked

    private void jLabel60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel60MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel60MouseClicked

    private void BTNviewAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNviewAgentActionPerformed

        AGENT_VIEW AA = new AGENT_VIEW();
        AA.setVisible(true);
        AA.pack();
        AA.setLocationRelativeTo(null);
        AA.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_BTNviewAgentActionPerformed

    private void LBLBrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LBLBrowse1ActionPerformed
        // TODO add your handling code here:
        Myfunc mf = new Myfunc();
        imagePth = mf.browseImage(LBLPIC);
    }//GEN-LAST:event_LBLBrowse1ActionPerformed

    private void BTNviewAgent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNviewAgent1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNviewAgent1ActionPerformed

    //VERIFY THE INFORMATION HAS THE SAME AS THE CURRENT DATABASE 
    public boolean verifData(){
    
        if(JTFusername.getText().equals("") && JTFpassword.getText().equals("")            )
        {
            JOptionPane.showMessageDialog(null, "One or more Field are Empty!");
            return false;
        }        
        else if (imagePth == null){
            JOptionPane.showMessageDialog(null, "No Image Selected!!");
            return false;
            
        }else{
            return true;
        }
    
//        return false;
    }
    
    public boolean isUsernameExist(String un){
        boolean uExist = false;
        Connection con = MyConnection.getConnection();
        PreparedStatement ps;
        ResultSet rs;
        
        try {
            ps = con.prepareStatement("SELECT * FROM `agent` WHERE `username` = ?");
            ps.setString(1, JTFusername.getText());
            
            rs = ps.executeQuery();
            
            if (rs.next()){
                uExist = true;
            }
            
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return uExist;
    }
    
    private void BTNADDAGENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNADDAGENTActionPerformed
        if (verifData()){
        Connection con = MyConnection.getConnection();
        PreparedStatement ps;
        
        try {

             ps = con.prepareStatement("INSERT INTO `agent`( `is_Archive`,`Agent_Fname`, `Agent_Lname`, `Agent_Phone`, `Agent_Pic`, `username`, `password`) VALUES (0,?,?,?,?,?,?)");
            ps.setString(1, JTFfname.getText());
            ps.setString(2, JTFlname.getText());
            ps.setString(3, JTFphone.getText());
            ps.setString(5, JTFusername.getText());
            ps.setString(6, JTFpassword.getText());
           
            InputStream img = new FileInputStream(new File(imagePth));
            
            ps.setBlob(4, img);
            
            if (isUsernameExist(JTFusername.getText())){
                JOptionPane.showMessageDialog(null, "Username Already Existed");
            }else {
                if(ps.executeUpdate() != 0){
                JOptionPane.showMessageDialog(null, "Account Created!");
                }
                else{
                JOptionPane.showMessageDialog(null, "Something Wrong");
                }
            }
            
           
        
 
                    } catch (Exception ex) {
            java.util.logging.Logger.getLogger(AGENT_ADD.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_BTNADDAGENTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AGENT_ADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AGENT_ADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AGENT_ADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AGENT_ADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AGENT_ADD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNADDAGENT;
    private javax.swing.JButton BTNAddAgent;
    private javax.swing.JButton BTNviewAgent;
    private javax.swing.JButton BTNviewAgent1;
    private javax.swing.JTextField JTFfname;
    private javax.swing.JTextField JTFlname;
    private javax.swing.JTextField JTFpassword;
    private javax.swing.JTextField JTFphone;
    private javax.swing.JTextField JTFusername;
    private javax.swing.JLabel LBLAgent;
    private javax.swing.JButton LBLBrowse;
    private javax.swing.JButton LBLBrowse1;
    private javax.swing.JButton LBLBrowse3;
    private javax.swing.JLabel LBLPIC;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel logo1;
    // End of variables declaration//GEN-END:variables
}
